### ISSUE TITLE
AttributeError: 'GeneInfo' object has no attribute 'reference_region'

### ISSUE THREAD

**Issue by rsalz** [ablab/IsoQuant#38] opened 2022-09-02 16:13 UTC
I am running isoquant with the following command:

```
isoquant.py --reference data/ref_grch38/gencode/GRCh38.primary_assembly.genome.fa.gz \
--genedb data/ref_grch38/gencode/gencode.v39.annotation.gtf --complete_genedb \
--fastq m64102e_220102_030451.flnc.fastq m64102e_220103_091618.flnc.fastq m64102e_211230_145358.flnc.fastq m64037e_211217_220808.flnc.fastq m64102e_211231_205239.flnc.fastq \
--data_type pacbio_ccs --fl_data \
--labels ca rp sa lp poly \
--check_canonical --count_exons --threads 20 \
--transcript_quantification with_ambiguous --gene_quantification unique_only \
--splice_correction_strategy default_pacbio --model_construction_strategy fl_pacbio -o five_conditions
```

and I get the following error:

```
2022-09-02 17:47:35,908 - INFO - Finished processing chromosome KI270394.1
2022-09-02 17:47:36,013 - INFO - Finished processing chromosome chrX
2022-09-02 17:47:36,498 - INFO - Finished processing chromosome chr16
2022-09-02 17:47:39,276 - INFO - Finished processing chromosome chr19
2022-09-02 17:47:40,351 - INFO - Finished processing chromosome chr22
2022-09-02 17:47:42,961 - INFO - Finished processing chromosome chr4
2022-09-02 17:47:47,377 - INFO - Finished processing chromosome chr7
2022-09-02 17:47:47,711 - INFO - Finished processing chromosome chr5
2022-09-02 17:47:48,731 - INFO - Finished processing chromosome chr8
2022-09-02 17:47:49,966 - INFO - Finished processing chromosome chr13
2022-09-02 17:47:51,609 - INFO - Finished processing chromosome chr21
2022-09-02 17:47:58,349 - INFO - Finished processing chromosome chr14
2022-09-02 17:48:01,096 - INFO - Finished processing chromosome chr3
2022-09-02 17:48:01,380 - INFO - Finished processing chromosome chr11
2022-09-02 17:48:02,311 - INFO - Finished processing chromosome chr12
2022-09-02 17:48:02,899 - INFO - Finished processing chromosome chr17
2022-09-02 17:48:06,444 - INFO - Finished processing chromosome chr10
2022-09-02 17:48:58,723 - INFO - Finished processing chromosome chr2
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/renees/miniconda3/envs/isoquant/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/renees/miniconda3/envs/isoquant/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/mnt/home2/renees/miniconda3/envs/isoquant/share/isoquant-3.0.0-0/src/dataset_processor.py", line 144, in construct_models_in_parallel
    tmp_gff_printer.dump(model_constructor)
  File "/mnt/home2/renees/miniconda3/envs/isoquant/share/isoquant-3.0.0-0/src/transcript_printer.py", line 98, in dump
    transcript_model_constructor.gene_info.reference_region:
AttributeError: 'GeneInfo' object has no attribute 'reference_region'
"""
```

I can't really tell how to fix this

**Comment by andrewprzh** [comment] 2022-09-06 12:12
Dear @rsalz 

Thank you for the bug report. The problem is in `--check_canonical` option. 
Should be fixed in the latest release https://github.com/ablab/IsoQuant/releases/tag/v3.0.1
Alternatively, you may remove this option.

Best
Andrey

**Comment by rsalz** [comment] 2022-09-07 09:41
Hi Andrey
I downloaded the tarball, untarred, went into the folder and ran `pip install -r requirements.txt`

I got the following error:

```
error: Command "gcc -pthread -B /home/renees/miniconda3/envs/isoquant/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/renees/miniconda3/envs/isoquant/include -fPIC -O2 -isystem /home/renees/miniconda3/envs/isoquant/include -fPIC -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Ibuild/src.linux-x86_64-3.1/numpy/core/src/private -Inumpy/core/include -Ibuild/src.linux-x86_64-3.1/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/renees/miniconda3/envs/isoquant/include/python3.10 -Ibuild/src.linux-x86_64-3.1/numpy/core/src/private -Ibuild/src.linux-x86_64-3.1/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.1/numpy/core/src/private -Ibuild/src.linux-x86_64-3.1/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.1/numpy/core/src/private -Ibuild/src.linux-x86_64-3.1/numpy/core/src/npymath -c build/src.linux-x86_64-3.1/numpy/core/src/multiarray/scalartypes.c -o build/temp.linux-x86_64-cpython-310/build/src.linux-x86_64-3.1/numpy/core/src/multiarray/scalartypes.o -MMD -MF build/temp.linux-x86_64-cpython-310/build/src.linux-x86_64-3.1/numpy/core/src/multiarray/scalartypes.o.d" failed with exit status 1
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure

      × Encountered error while trying to install package.
      ╰─> numpy

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I am using the isoquant conda environment built by the same command in the Quick Start.

**Comment by andrewprzh** [comment] 2022-09-07 15:53
Dear @rsalz 

I'm not sure why numpy installation raises an error.
Just got the message that IsoQuant 3.0.1 is now on bioconda, could you try installing it via conda?

Best
Andrey

**Comment by rsalz** [comment] 2022-09-08 11:44
Thanks Andrey, when I updated using conda the pipeline ran to completion. Great!
One question about the output- since I have multiple input samples, I am given one gtf file per sample. I see that in the output folder there are "combined" files containing transcript/gene counts/tpm across all samples but I would really like one combined GTF file too. Is that possible?

**Comment by andrewprzh** [comment] 2022-09-08 13:04
Dear @rsalz 

Yes, it is, in a slightly different way. I suggest to provide all five files as different replicas of a single sample, i.e. make a file listing all FASTQs/BAMs with their labels
`
m64102e_220102_030451.flnc.fastq:ca
m64102e_220103_091618.flnc.fastq:rp
m64102e_211230_145358.flnc.fastq:sa 
m64037e_211217_220808.flnc.fastq:lp
m64102e_211231_205239.flnc.fastq:poly
`
and add `--read_group file_name` option to obtain per-sample counts if you need them.
This will give you a single combined GTF and keep group counts.

For more information, you can take a look at some examples:
https://github.com/ablab/IsoQuant#examples

Best
Andrey

**Closed** 2022-09-11 21:38 UTC
