### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jackhump** [ablab/IsoQuant#19] opened 2021-04-20 14:55 UTC
Hi all, I was recommended to try out Isoquant by Anoushka Joglekar. I have 30 Isoseq runs (~90M FLNC reads total) so I'm looking for a way to process them all together to produce a merged GTF and a count matrix.  The package looks great and the documentation is really clear.

I'm using as input FLNC BAM files produced by isoseq3, aligned to hg38 and sorted with pbmm2 using default isoseq settings. I'm trying out TALON as well so the BAM files have the MD flag added on them by samtools calmd. I'm using a genedb created from GENCODE v30.   

I keep running in to the same error.  I tried installing isoquant through github/pip and through conda and I get the same error. 

I initially had a more elaborate command:

```
isoquant.py -d pacbio_ccs --polya_trimmed --fl_data --bam_list TALON/isoquant/test_isoquant_config.csv --reference /sc/arion/projects/ad-omics/data/references/hg38_reference/hg38.fa --genedb /sc/arion/projects/ad-omics/data/references/hg38_reference/GENCODE/gencode.v30.annotation.db --output TALON/isoquant/ --labels VA_2065 VA_2033 --sqanti_output --check_canonical --threads 4 --matching_strategy precise --model_construction_strategy default_ccs
```

but I found the same error occurred with the simpler command below.

```
isoquant.py -d pacbio_ccs --bam /sc/arion/projects/als-omics/microglia_isoseq/isoseq-pipeline/TALON/VA_2033/pbmm2/VA_2033.aligned.md.bam --reference /sc/arion/projects/ad-omics/data/references/hg38_reference/hg38.fa --genedb /sc/arion/projects/ad-omics/data/references/hg38_reference/GENCODE/gencode.v30.annotation.db --output TALON/isoquant/ --labels VA_2033 --threads 16
WARNING! Output folder already exists, some files may be overwritten
2021-04-20 10:38:34,622 - WARNING - Tmp folder already exists, some files may be overwritten
2021-04-20 10:38:34,622 - WARNING - TALON/isoquant/VA_2033 folder already exists, some files may be overwritten
2021-04-20 10:38:34,622 - WARNING - TALON/isoquant/VA_2033/aux folder already exists, some files may be overwritten
2021-04-20 10:38:34,623 - INFO -  === IsoQuant pipeline started === 
2021-04-20 10:38:34,623 - INFO - Loading gene database from /sc/arion/projects/ad-omics/data/references/hg38_reference/GENCODE/gencode.v30.annotation.db
2021-04-20 10:38:34,857 - INFO - Loading reference genome from /sc/arion/projects/ad-omics/data/references/hg38_reference/hg38.fa
2021-04-20 10:39:02,907 - INFO - Processing 1 sample
2021-04-20 10:39:02,907 - INFO - Processing sample VA_2033
2021-04-20 10:39:02,907 - INFO - Sample has 1 BAM file: /sc/arion/projects/als-omics/microglia_isoseq/isoseq-pipeline/TALON/VA_2033/pbmm2/VA_2033.aligned.md.bam
2021-04-20 10:39:03,618 - INFO - Processing chromosome chr15
2021-04-20 10:39:04,214 - INFO - Processing chromosome chr1
2021-04-20 10:39:04,258 - INFO - Processing chromosome chr14
2021-04-20 10:39:04,400 - INFO - Processing chromosome chr17
2021-04-20 10:39:04,770 - INFO - Processing chromosome chr11
2021-04-20 10:39:05,304 - INFO - Processing chromosome chr2
2021-04-20 10:39:05,440 - INFO - Processing chromosome chr12
2021-04-20 10:39:05,850 - INFO - Processing chromosome chr3
2021-04-20 10:39:06,104 - INFO - Processing chromosome chr19
2021-04-20 10:39:06,109 - INFO - Processing chromosome chr5
2021-04-20 10:39:06,370 - INFO - Processing chromosome chr16
2021-04-20 10:39:06,764 - INFO - Processing chromosome chr7
2021-04-20 10:39:07,076 - INFO - Processing chromosome chr6
2021-04-20 10:39:07,299 - INFO - Processing chromosome chr8
2021-04-20 10:39:07,662 - INFO - Processing chromosome chr4
2021-04-20 10:39:07,815 - INFO - Processing chromosome chr10
2021-04-20 10:39:07,876 - INFO - Processing chromosome chrX
2021-04-20 10:39:08,055 - INFO - Processing chromosome chr9
2021-04-20 10:39:08,105 - INFO - Processing chromosome chr22
2021-04-20 10:39:08,234 - INFO - Processing chromosome chr18
2021-04-20 10:39:08,454 - INFO - Processing chromosome chr13
2021-04-20 10:39:08,500 - INFO - Processing chromosome chr20
2021-04-20 10:39:08,591 - INFO - Processing chromosome chr21
2021-04-20 10:39:08,644 - INFO - Processing chromosome chrM
2021-04-20 10:39:08,689 - INFO - Processing chromosome chrY
IsoQuant failed with the following error, please, submit this issue to https://github.com/ablab/IsoQuant/issues
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/share/isoquant-1.2.0-1/src/dataset_processor.py", line 123, in process_in_parallel
    assignment_storage = alignment_processor.process()
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/share/isoquant-1.2.0-1/src/alignment_processor.py", line 52, in process
    self.process_single_file(b)
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/share/isoquant-1.2.0-1/src/alignment_processor.py", line 92, in process_single_file
    combined_profile = self.profile_constructor.construct_profiles(sorted_blocks, polya_info, cage_hits)
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/share/isoquant-1.2.0-1/src/long_read_profiles.py", line 192, in construct_profiles
    polya_info.external_polyt_pos)
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/share/isoquant-1.2.0-1/src/long_read_profiles.py", line 49, in construct_intron_profile
    mapped_region = (sorted_blocks[0][0], sorted_blocks[-1][1])
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/bin/isoquant.py", line 472, in <module>
    main(sys.argv[1:])
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/bin/isoquant.py", line 465, in main
    run_pipeline(args)
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/bin/isoquant.py", line 446, in run_pipeline
    dataset_processor.process_all_samples(args.input_data)
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/share/isoquant-1.2.0-1/src/dataset_processor.py", line 156, in process_all_samples
    self.process_sample(sample)
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/share/isoquant-1.2.0-1/src/dataset_processor.py", line 177, in process_sample
    for (chr_id, c) in chrom_clusters])
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
IndexError: list index out of range
```

I also tried extracting just chr21 to create a minimal example BAM and it still failed with the same error.

Please let me know your thoughts. If there's anything else you need me to provide, let me know. 

best wishes,

Jack Humphrey

**Comment by andrewprzh** [comment] 2021-04-20 20:04
Dear Jack!
Thank you for your report!

This error seems very odd, since sorted_blocks are basically read exons and "index out of range" suggests that they are empty.
Do you know whether your BAM files contain CIGAR strings?

In any case, such cases should be handled in a more user-friendly way.
Could you send me a minimal BAM file that, as you indicated, reproduces the error?
You can send them here or directly to my address specified in my GitHub profile.

All the best
Andrey

**Comment by jackhump** [comment] 2021-04-20 20:29
aha, I was having a similar error with TALON, as the BAM files are aligned with pbmm2 which uses the new X/= format for CIGAR strings rather than the older "M" for mapping.

I've emailed you the minimal BAM file.

**Comment by andrewprzh** [comment] 2021-04-20 22:39
Thanks for the data!

Yes, exactly, this was the reason.
Here is the fix https://github.com/ablab/IsoQuant/commit/88393fec19a34e38729d2be6d15b29811168a5a0
Currently this fix is in master branch, but I'll make 1.2.1 bugfix release soon. 1.3 will come some time later.

Unrelated, --check_canonical might also be a bit buggy, so 1.2.1 will include that fix as well.

Best
Andrey

**Comment by jackhump** [comment] 2021-04-20 23:25
You're a star, thank you! I'll try it out.

On Apr 20, 2021 6:40 PM, Andrey Prjibelski ***@***.***> wrote:

Thanks for the data!

Yes, exactly, this was the reason.
Here is the fix 88393fe<https://github.com/ablab/IsoQuant/commit/88393fec19a34e38729d2be6d15b29811168a5a0>
Currently this fix is in master branch, but I'll make 1.2.1 bugfix release soon. 1.3 will come some time later.

Unrelated, --check_canonical might also be a bit buggy, so 1.2.1 will include that fix as well.

Best
Andrey

**Comment by andrewprzh** [comment] 2021-04-21 11:04
Dear Jack

Released 1.2.1 https://github.com/ablab/IsoQuant/releases/tag/v1.2.1
Should be on conda now as well https://github.com/bioconda/bioconda-recipes/pull/28131

**Comment by jackhump** [comment] 2021-04-21 15:33
Dear Andrey,

Thanks for the fixes. My minimal example BAM (for chr21) successfully completed. However, running on an entire sample it still failed. I have traced it down to another minimal example on chr1. I tried running on unmapped reads, alternate contig chromosomes, mitochondrial chromosomes, all passed. 

Here is the error:

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/share/isoquant-1.2.1-0/src/dataset_processor.py", line 123, in process_in_parallel
    assignment_storage = alignment_processor.process()
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/share/isoquant-1.2.1-0/src/alignment_processor.py", line 52, in process
    self.process_single_file(b)
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/share/isoquant-1.2.1-0/src/alignment_processor.py", line 95, in process_single_file
    combined_profile = self.profile_constructor.construct_profiles(sorted_blocks, polya_info, cage_hits)
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/share/isoquant-1.2.1-0/src/long_read_profiles.py", line 192, in construct_profiles
    polya_info.external_polyt_pos)
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/share/isoquant-1.2.1-0/src/long_read_profiles.py", line 49, in construct_intron_profile
    mapped_region = (sorted_blocks[0][0], sorted_blocks[-1][1])
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/bin/isoquant.py", line 472, in <module>
    main(sys.argv[1:])
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/bin/isoquant.py", line 465, in main
    run_pipeline(args)
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/bin/isoquant.py", line 446, in run_pipeline
    dataset_processor.process_all_samples(args.input_data)
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/share/isoquant-1.2.1-0/src/dataset_processor.py", line 156, in process_all_samples
    self.process_sample(sample)
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/share/isoquant-1.2.1-0/src/dataset_processor.py", line 177, in process_sample
    for (chr_id, c) in chrom_clusters])
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/sc/arion/projects/als-omics/conda/envs/isoquant/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
IndexError: list index out of range
```

I've emailed you the BAM file for you to check out. Thanks for all your help! The results I got for the individual chromosomes look really exciting.

**Comment by andrewprzh** [comment] 2021-04-22 17:22
Thanks for the data! 
Sorry, my bad - was did not fix usage of =/X completely. I updated 1.2.1 version and submitted it to bioconda, should be there after a while. Hope this time everything should be fine :)
Unfortunately, your previous run with 1.2.1 is buggy and doesn't make much sense.. Sorry for that.

I'll let you know once release is accepted on bioconda.

Best
Andrey

**Comment by jackhump** [comment] 2021-04-22 19:11
Hi Andrey,

just to confirm, did the second test BAM file I sent now run without errors with your latest version?

**Comment by andrewprzh** [comment] 2021-04-23 08:32
Dear Jack

Yes, it works fine on both. I should've checked results the first time to realize they don't make sense. Now they seem ok.

Bioconda accepted my PR, but since release number remains the same (1.2.1), I'm not sure whether it will be upgraded simply by running conda install or you'll need to install from new environment.

Let me know if any other problems arise!

Best
Andrey

**Comment by jackhump** [comment] 2021-05-04 21:23
Hi Andrey,

Thanks for all your help!

I got Isoquant to run successfully over the weekend on all 30 samples.  If you're curious for benchmarking, with 8 threads it took 75 hours to process 88M total reads, with a peak memory usage of 135GB.  I now have output files for each sample, as well as a combined transcript and gene count table for the 30 samples together.

However, I'm not sure how to proceed as I don't think the transcript count table includes the novel transcripts. 

How does isoquant handle the merging of novel transcripts between replicate samples? Ideally I would like to do additional filtering using SQANTI on a single GTF file containing the merged transcripts all the samples together, along with a count matrix for those transcripts, for use with SWAN. 

Please let me know if I'm misunderstanding the output. 

best,

Jack

**Comment by andrewprzh** [comment] 2021-05-05 12:26
Hi Jack

Thank you for performance stats! I'm currently working on this matter and expect next version to consume significantly less RAM.

> However, I'm not sure how to proceed as I don't think the transcript count table includes the novel transcripts.
IsoQuant generates 2 files with transcript counts:
SAMPLE_ID.transcript_counts.tsv - counts for reference isoforms (original IDs)
SAMPLE_ID.transcript_models_counts.tsv - counts for constructed transcript models (new IDs, includes both known and novel)
You can find complete output description here https://github.com/ablab/IsoQuant#sec3.3

>How does isoquant handle the merging of novel transcripts between replicate samples? Ideally I would like to do additional >filtering using SQANTI on a single GTF file containing the merged transcripts all the samples together, along with a count >matrix for those transcripts, for use with SWAN.

Could you please send me the command lines you used?
IsoQuant creates a single GTF for each sample. If you provide all files as a single sample you'll get merged GTF. However, IsoQuant currently does not take into account whether a transcript is supported by reads from different replicates or not. Only the total number of reads supporting novel isoform is what matters.

What you can do, for example, is to run IsoQuant once more on combined GTF obtained from all samples altogether (instead of reference annotation), but provide each sample separately. Thus, you will get transcript counts table for both known and novel isoforms for all samples. I guess this table can be used for SWAN, and also can be used to e.g. filter novel isoforms that express only in a single sample.

Hope that answers at least some of you question, I'm ready for more :)

All the best
Andrey

**Comment by jackhump** [comment] 2021-05-05 16:07
I see, so you propose I run it first on a concatenated BAM file of all the samples to get a single merged GTF, and then run a second time with samples separated to get a transcript count table that includes all the novel counts.

This seems quite inefficient, no? 

What about if I set read groups in the concatenated BAM file where each sample has its own read group? Would then using the `--read_group` flag pull out the counts per sample?

**Comment by andrewprzh** [comment] 2021-05-05 19:01
In fact, you don't need to concatenate all BAM files, you can simply create a text file listing all of them (one per line, no blank lines) and it provide via --bam_list. They all will be treated as a single sample and a single merged GTF will be created.

>This seems quite inefficient, no?
Yes, you are right about inefficiency. Unfortunately, current functionality does not allow to count novel isoforms by file of origin / read group as this information is lost during transcript model construction. I will think whether this can be implemented quickly.

>What about if I set read groups in the concatenated BAM file where each sample has its own read group? Would then using the --read_group flag pull out the counts per sample?
That would do the per-sample counts, but unfortunately only for reference transcript counts.

Best
Andrey

**Comment by andrewprzh** [comment] 2021-05-05 22:55
After thinking a bit I think there are 2 relatively easy ways:
1. There is file called SAMPLE.transcript_models_reads.tsv which contains ids of all reads assigned to an isoform (both known and novel). So once you have merged GTF from all samples you can derive counts from this file based on read ids (as you know which read comes from which file).
2. I realized that implementing grouped counts for novel models is fairly easy, so I will do it. Groups can be specified either via BAM flag, or via a separate TSV file (which I presume could be even faster to get than modify all bam files).

In one of the next releases I will implement generation of merged GTF for all samples.

Best
Andrey

**Comment by jackhump** [comment] 2021-05-06 15:44
I see. So in my first run I used the following command, forgive the curly braces for snakemake:
```
        "isoquant.py -d pacbio_ccs --polya_trimmed --fl_data --bam_list {input.bam_list} "
        "--reference {reference_fasta} --genedb {input.db} --output {out_folder}isoquant/{data_code}/ "
        "--labels {params.labels} "
        "--sqanti_output  --threads {isoquant_threads} "
        "--matching_strategy {matching_strategy} "
        "--model_construction_strategy {model_strategy} "
```

So in this case I provided a list of BAM files and a set of labels, which were the sample IDs.  So if I run this command without the `--labels` argument would isoquant create a single combined GTF?

**Comment by andrewprzh** [comment] 2021-05-06 17:16
BAM file list is interpreted as follows: BAM files on consecutive lines are treated as a single sample, and blank lines are used for sample separation. E.g.
```
sample1.1.bam
sample1.2.bam

sample2.1.bam
sample2.2.bam
```
I guess you did everything right since the number of labels should be equal to the number of sample (IsoQuant should check it).
Thus, if you remove blank lines you should get a combined GTF for all BAMs.

I cannot say for sure, but I guess I will implement per-group isoform counting during next week.

**Comment by andrewprzh** [comment] 2021-10-14 12:09
Hi!

Took a bit more, than expected:)
In IsoQuant 2.0 you can add `--read_group file_name` and it will create an expression table with a separate column for each replica within the sample. You can also add a label for each replica using colon, e.g.

```
replicate1.fastq:R1
replicate2.fastq:R2
replicate3.fastq:R3
```

The resulting GTF will be constructed from all 3 files, and the expression table will contain 3 columns: R1, R2, R3.

Yes, it will not create a single GTF for all samples (one GTF per sample), but I guess you can use this for your work.

Best
Andrey

**Closed by andrewprzh** 2021-10-14 12:09 UTC
