### ISSUE TITLE
AssertionError assert len(self.gene_info.all_isoforms_exons[refrenence_isoform_id]) == 1

### ISSUE THREAD

**Issue by LiChen1990** [ablab/IsoQuant#51] opened 2023-01-12 02:31 UTC
When I used the command below to run the program, I got one AssertionError and I don't know what's wrong with it?

isoquant.py --reference  GRCh37.primary_assembly.genome.fa     --genedb  gencode.v37lift37.annotation.gtf   --fastq PEC_lncRNA_MSSM_DLPFC_mRNA_PacBioRSII_1to2kbhighQV.fastq.gz    --data_type pacbio_ccs   -o isoquant_OUTPUT_FOLDER  --sqanti_output 

2023-01-12 03:02:29,559 - INFO - Processing assigned reads 00_PEC_lncRNA_MSSM_DLPFC_mRNA_PacBioRSII_1to2kbhighQV.fastq
2023-01-12 03:02:29,580 - INFO - Loading read assignments from isoquant_OUTPUT_FOLDER/00_PEC_lncRNA_MSSM_DLPFC_mRNA_PacBioRSII_1to2kbhighQV.fastq/aux/00_PEC_lncRNA_MSSM_DLPFC_mRNA_PacBioRSII_1to2kbhighQV.fastq.save_chr1
2023-01-12 03:02:35,333 - INFO - Loading read assignments from isoquant_OUTPUT_FOLDER/00_PEC_lncRNA_MSSM_DLPFC_mRNA_PacBioRSII_1to2kbhighQV.fastq/aux/00_PEC_lncRNA_MSSM_DLPFC_mRNA_PacBioRSII_1to2kbhighQV.fastq.save_chr10
2023-01-12 03:02:37,362 - INFO - Loading read assignments from isoquant_OUTPUT_FOLDER/00_PEC_lncRNA_MSSM_DLPFC_mRNA_PacBioRSII_1to2kbhighQV.fastq/aux/00_PEC_lncRNA_MSSM_DLPFC_mRNA_PacBioRSII_1to2kbhighQV.fastq.save_chr11
IsoQuant failed with the following error, please, submit this issue to https://github.com/ablab/IsoQuant/issues
Traceback (most recent call last):
  File "/storage/yangjianLab/chenli/softwares/condalocal/tensorflow20_py36/bin/isoquant.py", line 474, in <module>
    main(sys.argv[1:])
  File "/storage/yangjianLab/chenli/softwares/condalocal/tensorflow20_py36/bin/isoquant.py", line 468, in main
    run_pipeline(args)
  File "/storage/yangjianLab/chenli/softwares/condalocal/tensorflow20_py36/bin/isoquant.py", line 454, in run_pipeline
    dataset_processor.process_all_samples(args.input_data)
  File "/storage/yangjianLab/chenli/softwares/condalocal/tensorflow20_py36/share/isoquant-2.1.1-0/src/dataset_processor.py", line 233, in process_all_samples
    self.process_sample(sample)
  File "/storage/yangjianLab/chenli/softwares/condalocal/tensorflow20_py36/share/isoquant-2.1.1-0/src/dataset_processor.py", line 260, in process_sample
    self.process_assigned_reads(sample, saves_file)
  File "/storage/yangjianLab/chenli/softwares/condalocal/tensorflow20_py36/share/isoquant-2.1.1-0/src/dataset_processor.py", line 333, in process_assigned_reads
    model_constructor.process(assignment_storage)
  File "/storage/yangjianLab/chenli/softwares/condalocal/tensorflow20_py36/share/isoquant-2.1.1-0/src/graph_based_model_construnction.py", line 116, in process
    self.construnct_assignment_based_isoforms(read_assignment_storage)
  File "/storage/yangjianLab/chenli/softwares/condalocal/tensorflow20_py36/share/isoquant-2.1.1-0/src/graph_based_model_construnction.py", line 274, in construnct_assignment_based_isoforms
    assert len(self.gene_info.all_isoforms_exons[refrenence_isoform_id]) == 1
AssertionError

**Comment by andrewprzh** [comment] 2023-01-12 11:17
Dear @LiChen1990 

Could you try the latest IsoQuant 3.1 and check whether the issue reproduces?

Best
Andrey

**Comment by LiChen1990** [comment] 2023-01-15 12:04
Dear Andrey:

Thanks for your kind replies.

I used the latest and these errors can be reproduced.

I found the errors are due to the gtf file. It's ok to use the GhCR38 
version 
(https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_42/gencode.v42.annotation.gtf.gz) 
but not GhCR37 gtf file 
(https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_42/GRCh37_mapping/gencode.v42lift37.annotation.gtf.gz).

Best wishes

Li Chen

On 2023-01-12 12:17, Andrey Prjibelski wrote:

> Dear @LiChen1990 [1]
> 
> Could you try the latest IsoQuant 3.1 and check whether the issue 
> reproduces?
> 
> Best
> Andrey
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>

-- 
Thanks
Best wishes
Li Chen

Humboldt-Universitaet zu Berlin
Dep.Plant Cell and Molecular Biology
Institute for Biology
Philippstr. 13 (House 22)
10115 Berlin, Germany
https://www2.hu-berlin.de/biologie/flower/index.php

Links:
------
[1] https://github.com/LiChen1990
[2] https://github.com/ablab/IsoQuant/issues/51#issuecomment-1380177338
[3]

**Comment by andrewprzh** [comment] 2023-01-15 19:49
Dear Li Chen

Glad you found a workaround.
Thank you for the links, will try to figure out the reason for this failure.

Best
Andrey

**Comment by andrewprzh** [comment] 2023-01-16 12:03
Dear @LiChen1990 

Indeed, there is sligltly awkward isoform ENST00000304061.8_4 containing an intron of length 0, which seems to be a corner case:
chr14   HAVANA  exon    73957638        73957981 
chr14   HAVANA  exon    73957982        73960098 

I'll think what can be done to avoid the failure. Thanks for the report!

Best
Andrey

**Comment by andrewprzh** [comment] 2023-03-28 15:17
Please re-open if the issue is still not resolved in the latest 3.2.

Best
Andrey

**Closed by andrewprzh** 2023-03-28 15:17 UTC
Labels: bug
